-- Insert all plans for all tiers and durations into subscription_plans
INSERT INTO public.subscription_plans (name, duration_type, price, features) VALUES
-- Tier 1: Scanner Only
('Tier 1: Scanner Only', 'weekly', 19.00, '{"features": ["Real-time triangular arbitrage opportunities on Binance & Bybit", "Historical data: 7 days of opportunity tracking", "Basic filters: Minimum profit threshold settings", "Assumed Monthly Profit: $150"]}'),
('Tier 1: Scanner Only', 'monthly', 60.00, '{"features": ["Real-time triangular arbitrage opportunities on Binance & Bybit", "Historical data: 7 days of opportunity tracking", "Basic filters: Minimum profit threshold settings", "Assumed Monthly Profit: $150"]}'),
('Tier 1: Scanner Only', 'quarterly', 150.00, '{"features": ["Real-time triangular arbitrage opportunities on Binance & Bybit", "Historical data: 7 days of opportunity tracking", "Basic filters: Minimum profit threshold settings", "Assumed Monthly Profit: $150"]}'),
-- Tier 2: Trader Pro ($500 Max)
('Tier 2: Trader Pro ($500 Max)', 'weekly', 195.00, '{"features": ["Everything in Tier 1 plus:", "Automated trading via Binance & Bybit APIs", "Position limit: $500 maximum per trade", "Basic analytics: Trade history, P&L tracking", "Assumed Monthly Profit: $1,500"]}'),
('Tier 2: Trader Pro ($500 Max)', 'monthly', 600.00, '{"features": ["Everything in Tier 1 plus:", "Automated trading via Binance & Bybit APIs", "Position limit: $500 maximum per trade", "Basic analytics: Trade history, P&L tracking", "Assumed Monthly Profit: $1,500"]}'),
('Tier 2: Trader Pro ($500 Max)', 'quarterly', 1500.00, '{"features": ["Everything in Tier 1 plus:", "Automated trading via Binance & Bybit APIs", "Position limit: $500 maximum per trade", "Basic analytics: Trade history, P&L tracking", "Assumed Monthly Profit: $1,500"]}'),
-- Tier 3: Trader Elite ($1,000 Max)
('Tier 3: Trader Elite ($1,000 Max)', 'weekly', 395.00, '{"features": ["Everything in Tier 2 plus:", "Position limit: $1,000 maximum per trade", "Priority execution: Faster opportunity detection & execution", "Advanced analytics: Success rate tracking, Average profit per trade, Best performing pairs analysis, Time-of-day performance metrics", "Historical data: 90 days", "Custom settings: Personalized trading parameters", "Priority support: Email support with faster response", "Assumed Monthly Profit: $3,000"]}'),
('Tier 3: Trader Elite ($1,000 Max)', 'monthly', 1200.00, '{"features": ["Everything in Tier 2 plus:", "Position limit: $1,000 maximum per trade", "Priority execution: Faster opportunity detection & execution", "Advanced analytics: Success rate tracking, Average profit per trade, Best performing pairs analysis, Time-of-day performance metrics", "Historical data: 90 days", "Custom settings: Personalized trading parameters", "Priority support: Email support with faster response", "Assumed Monthly Profit: $3,000"]}'),
('Tier 3: Trader Elite ($1,000 Max)', 'quarterly', 3000.00, '{"features": ["Everything in Tier 2 plus:", "Position limit: $1,000 maximum per trade", "Priority execution: Faster opportunity detection & execution", "Advanced analytics: Success rate tracking, Average profit per trade, Best performing pairs analysis, Time-of-day performance metrics", "Historical data: 90 days", "Custom settings: Personalized trading parameters", "Priority support: Email support with faster response", "Assumed Monthly Profit: $3,000"]}');
